desc = "Types, Traits and support for Character Sets, Encodings, and CSEs (Character Set Encodings)"
keywords = ["Strings", "Characters", "Character Sets", "Encodings"]
license = "MIT"
name = "CharSetEncodings"
uuid = "cb9422de-a9d8-5b68-86db-ff05833ab307"
repo = "https://github.com/JuliaString/CharSetEncodings.jl.git"
